# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Truverus' do
   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'SVProgressHUD'
  pod 'Kingfisher'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'
  pod 'XCDYouTubeKit', '~> 2.7'
  pod 'SwiftyJSON', '~> 4.2.0'
  pod 'GoogleSignIn'
  pod 'SnapKit', '~> 4.0.0'
  pod 'GoogleSignIn'
  pod 'TaggerKit', :git => 'https://github.com/nekonora/TaggerKit.git'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for Truverus
end
